### ISSUE TITLE
Non application/json content type

### ISSUE THREAD

**Issue by MaximKeegan** [magnetsystems/r2m-sdk-ios#5]
I'm receiving from server content-type: application/hal+json;charset=UTF-8. And app crashes with 

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Assertion failed with expression ([responseObject isKindOfClass:[NSDictionary class]]) in MMRestTransporter.m:480 -[MMRestTransporter executeSuccessBlock:platformReturnType:controllerReturnType:responseObject:responseClass:]. responseObject should be a dictionary'
```
Because AFNetworking return nil for non acceptable content type.
It's possible to set acceptable content type for request?

**Comment by etexier** [comment]
Hi @MaximKeegan , 

Have you tried declaring a Request Accept header? 
To do it:
 "Add REST API->(in the "Header" section, click "Add New"), then enter out for "key" Accept and "value", say, application/hal+json . 

Note that the "value" entry only matters if you want to call "Test API". 

Once you call "Generate", you should see that the generated method now includes an "accept" argument which you can customize say by passing "application/hal+json" as value.
